### Exercicios Numpy

- Crie um array com 10 elementos usando a função arange
Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape
- Crie duas matrizes bidimensionais com valores aleatórios
calcule a transposta de cada matriz
multiplique as duas matrizes
- Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?
- Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha
- Crie um vetor nulo de tamanho 10
Como encontrar o tamanho da memória de qualquer matriz
- Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
- Crie um vetor com valores que variam de 10 a 49
Inverter um vetor (o primeiro elemento se torna o último)
- Crie uma matriz 3x3 com valores que variam de 0 a 8
- Crie uma matriz de identidade 3x3
- Crie uma matriz 3x3x3 com valores aleatórios
- Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
- Crie um vetor aleatório de tamanho 30 e encontre o valor médio
- Crie uma matriz 2D com 1 na borda e 0 dentro
- Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
- Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
- Subtrair a média de cada linha de uma matriz
- Como encontrar o valor mais frequente em uma matriz?
- Crie uma matriz a partir de um arquivo
- Crie uma matriz com valores aletaórios e salve para um arquivo

In [5]:
import numpy as np

__Contruir matrizes 2D__

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array1 = np.arange(10).reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
array2 = np.arange(11,21).reshape(2,5)
array2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
array3 = array1 *1.5
array3

array([[ 0. ,  1.5,  3. ,  4.5,  6. ],
       [ 7.5,  9. , 10.5, 12. , 13.5]])

__Gerar números aleatórios:__

In [45]:
np.random.randint(6, size=10)

array([1, 0, 5, 1, 0, 1, 0, 4, 4, 5])

In [47]:
np.random.randint(8,size=20)

array([4, 2, 1, 3, 5, 2, 3, 3, 1, 5, 4, 1, 0, 2, 4, 5, 6, 5, 3, 3])

In [40]:
np.random.randint(5, size=(2, 4))

array([[4, 3, 3, 3],
       [2, 1, 2, 4]])

In [64]:
np.random.randint(5, size=(3, 2))

array([[2, 3],
       [1, 0],
       [2, 0]])

In [41]:
np.random.rand(3,2)

array([[0.43491318, 0.39067016],
       [0.01586935, 0.6287633 ],
       [0.13773786, 0.04486704]])

In [63]:
np.random.rand(3,5)

array([[0.29854282, 0.90269497, 0.66701976, 0.56556393, 0.8462924 ],
       [0.66579137, 0.07627006, 0.96731577, 0.15542638, 0.07698993],
       [0.58836723, 0.9337381 , 0.31914343, 0.05740478, 0.47041819]])

__Transposta__

In [66]:
np.transpose(array1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [67]:
np.transpose(array3)

array([[ 0. ,  7.5],
       [ 1.5,  9. ],
       [ 3. , 10.5],
       [ 4.5, 12. ],
       [ 6. , 13.5]])

In [69]:
multiplicar = array1 * array3
multiplicar

array([[  0. ,   1.5,   6. ,  13.5,  24. ],
       [ 37.5,  54. ,  73.5,  96. , 121.5]])

__Salvar *npArray* em um arquivo__

In [81]:
np.savetxt('numpy_teste.txt', array1, delimiter=",")

In [88]:
np.savetxt('numpy_teste02.txt', array3 * multiplicar, delimiter=",")

__Verificar tamanho do arquivo (em bytes)__

In [79]:
import os

In [82]:
os.path.getsize('numpy_teste.txt')

250

In [89]:
os.path.getsize('numpy_teste02.txt')

250

In [90]:
os.stat('numpy_teste.txt').st_size

250

__Combinar linha a linha de matrizes (np.concatenate):__

In [105]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
array2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [107]:
np.concatenate((array1, array2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [108]:
np.concatenate((array1, array2), axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [110]:
np.concatenate((array1, array2), axis=1)

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [111]:
np.concatenate((array1, array2), axis=None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

__Criar um vetor nulo__

In [231]:
np.empty([2])

array([1.5e-323, 1.5e-323])

In [187]:
np.empty([10], dtype=int)

array([     94425306430032,                   0,        481036337257,
              450971566188,        416611827811,        197568495730,
              416611827821,        171798691960, 2482730743378214953,
       8319593459853046074])

In [119]:
np.empty([0, 0])

array([], shape=(0, 0), dtype=float64)

__Tamanho de memória de uma matriz__

In [120]:
print("%d bytes" % (array1.size * array1.itemsize))

80 bytes


In [121]:
print("%d bytes" % (array2.size * array2.itemsize))

80 bytes


In [123]:
print("%d bytes" % (multiplicar.size * multiplicar.itemsize))

80 bytes


__Reverter valores de uma matriz__

In [128]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
array1[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [136]:
np.flip(array1, axis=None)

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

__Inverter um vetor__

In [138]:
vetor = np.arange(10)
vetor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
vetor[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [140]:
np.flip(vetor, axis=None)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

__Matrix 3x3 com valores que variam de 0 a 8__

In [188]:
np.random.randint(9, size=(3, 3))

array([[7, 3, 2],
       [2, 6, 5],
       [4, 5, 5]])

__Matriz identidade__ (squared array with ones on the main diagonal)

In [134]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [141]:
np.identity(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [211]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

__Matriz 3x3 valores aleatorios__

In [194]:
np.random.randint(5, size=(3, 3))

array([[4, 4, 1],
       [0, 3, 1],
       [3, 2, 0]])

__Valores maximos e mínimos de uma matriz__

In [179]:
array4 = np.arange(100).reshape(10,10)

In [180]:
array4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
array4 .max()

99

In [182]:
array4 .min()

0

 __Vetor aleatório de tamanho 30 e o valor médio__

In [203]:
array5 = np.arange(30)
array5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [205]:
np.mean(array5)

14.5

__Matriz 2D com 1 na borda e 0 dentro__

In [242]:
identidade = np.identity(3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [279]:
matrix_id = np.random.randint(2, size=(3, 3))

for i in range(3):
    for j in range(3):
        if i == j:
            matrix_id[i][j] = 0
        else:
            matrix_id[i][j] = 1
        
matrix_id

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

__Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal__

In [291]:
matrix_id = np.random.randint(2, size=(5, 5))

for i in range(5):
    for j in range(5):
        if i < j:
            matrix_id[i][j] = 0
        else:
            if i == j:
                matrix_id[i][j] = 0            
            else:
                matrix_id[i][j] = np.random.randint(5)
        
matrix_id

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [4, 0, 0, 0, 0],
       [2, 0, 1, 0, 0],
       [0, 4, 3, 3, 0]])

__Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)__


__Subtrair a média de cada linha de uma matriz__

__Como encontrar o valor mais frequente em uma matriz?__

__Crie uma matriz a partir de um arquivo__

__Crie uma matriz com valores aletaórios e salve para um arquivo__