<a href="https://colab.research.google.com/github/mrcrdg/jupyter_set/blob/master/Perceptron_OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron OR Implementation

## Setting up the environmentm

The Keras framework has been implemented inside the Google Tensorflow API on version 2.0. The Keras framework takes advantage of the optimizations for GPU and also TPU

The first thing we should do is to update Google Colab tensorflow version <strong>this has to be done at every notebook created</strong>. The tool we'll be using for that is the `pip` tool. It is important that we restart the environment after finishing the installation;

In [ ]:
! pip install tensorflow==2

In [ ]:
import tensorflow as tf
print(tf.__version__) # Check the version of the tensorflow library

2.0.0


## Create the input dataset

We will also use numpy, thus the import:

In [ ]:
import numpy as np

Create the truth table for the OR operation:

In [ ]:
or_truth_table = np.array([[0,0,0],
                           [0,1,1],
                           [1,0,1],
                           [1,1,1]])

## Creating a Sequential Model

Import and instantiate the Sequential model

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
model = Sequential()

Create a layer with a single neuron. The Dense layer represents a layer of neurons that are completely interconnected with the previous and next layer.

In [ ]:
from tensorflow.keras.layers import Dense

In [ ]:
model.add(Dense(units=1, input_dim=2))

Now we need to compile the model

In [ ]:
model.compile(loss="mean_squared_error", optimizer="sgd")

Split our dataset into input and expected values;

In [ ]:
X_data = or_truth_table[:,[0,1]]

In [ ]:
Y_data = or_truth_table[:,2]

Perform the training (`fit`) operations.

In [ ]:
model.fit(x=X_data, y=Y_data, epochs=200, verbose=0)

Check the error value (`loss`) when predicting using the dataset, i.e., how far off we are from the correct answer. 

In [ ]:
loss_and_metrics = model.evaluate(X_data, Y_data)
print(loss_and_metrics)

4/1 [========================================================================================================================] - 0s 599us/sample - loss: 0.0819
0.08190849423408508


Now it is time to make predictions using our trained model

In [ ]:
prediction = model.predict(X_data)

In [ ]:
print(prediction)

[[0.28700256]
 [0.75856614]
 [0.75304747]
 [1.224611  ]]


Convert the output to the desired format:

In [ ]:
print(np.round(prediction))

[[0.]
 [1.]
 [1.]
 [1.]]


In [ ]:
print(Y_data)

[0 1 1 1]
